on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8u292, 8, 11, 11.0.12, 17-ea]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{matrix.java}}  
    - run: ant -buildfile AnagramGame/build.xml jar
    - run: ant -buildfile ServiceSample/build.xml jar
