on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]
    steps:
    - uses: actions/checkout@v2
    - run: java -version
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}  
    - run: java -version
    - run: ant ../AnagramGame/build.xml
      
   
