on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 13, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}} 
    - run: ant -buildfile AnagramGame/build.xml jar
    - run: ant -buildfile ServiceSample/build.xml jar
    - run: mvn -B package --file JavaFX/HelloFX/pom.xml  
    - run: mvn -B package --file AnagramGameMaven/com.wordlibrary/pom.xml  
    - run: mvn -B package --file AnagramGameMaven/com.toy.anagram/pom.xml  
 
  
      
   
